import type { Metadata } from "next";
import { Contact } from "@/components/about/Contact";
import { INSTITUTIONS, PROFILES, TIMELINE, VERIFIABLE } from "@/lib/about";

export const metadata: Metadata = {
  title: "About & Contact",
  description:
    "Khondoker Zobaed Hassan — photographer, 3D documentarian and heritage " +
    "researcher in Dhaka. Career, institutions, and how to get in touch.",
};

/**
 * About.
 *
 * By the time a visitor arrives here they have seen the evidence. About's
 * job is not to prove anything — it is to connect what they have already
 * seen, which is why the two structural elements are a line and a list of
 * institutions rather than a paragraph of adjectives.
 */
export default function AboutPage() {
  return (
    <div className="mx-auto max-w-2xl px-6 py-16">
      <h1 className="font-serif text-3xl leading-tight text-balance sm:text-4xl">
        I make records of things that may not be here tomorrow.
      </h1>

      <div className="mt-10 flex flex-col gap-5 text-[17px] leading-[1.75]">
        <p>
          I enrolled at American International University-Bangladesh in 2012 to
          study Computer Science, and left in 2019 having completed majors in
          two different departments — Computer Science, and Journalism and Mass
          Communication. As far as the university is aware, no other Computer
          Science student has done this.
        </p>
        <p>
          That is the short answer to how one person ends up doing
          photogrammetry, running a studio, teaching virtual reality and
          writing heritage papers. I was never asked to choose between the
          machine and the story.
        </p>
      </div>

      <section aria-labelledby="teaching" className="mt-12">
        <h2
          id="teaching"
          className="font-mono text-xs tracking-widest text-neutral-500 uppercase"
        >
          Teaching
        </h2>
        <p className="mt-4 text-[17px] leading-[1.75]">
          I have run more than twenty workshops on photography, retouching,
          virtual reality and augmented reality since 2012 — first through the
          AIUB Photography Club, then STUDIO 13, and as an Instructor at the
          AIUB Continuing Education Center. I am still invited back to teach. In
          July 2026 I ran an augmented reality workshop for Animation and
          Journalism students in the same building where I was once a student.
        </p>
      </section>

      <section aria-labelledby="now" className="mt-12">
        <h2
          id="now"
          className="font-mono text-xs tracking-widest text-neutral-500 uppercase"
        >
          Now
        </h2>
        <div className="mt-4 flex flex-col gap-5 text-[17px] leading-[1.75]">
          <p>
            I am CEO of Keerti Creations in Dhaka, where the work is
            photogrammetry, 3D animation, 3D modelling and 3D printing. The
            heritage documentation is separate from that: most of it is
            uncommissioned, done because the object was in front of me and
            nobody else was recording it.
          </p>
          <p>
            I also work with local generative AI models. That is practice, not
            published work, and nothing generated by it appears anywhere on
            this site except where it is labelled as exactly that.
          </p>
        </div>
      </section>

      <section aria-labelledby="timeline" className="mt-16">
        <h2
          id="timeline"
          className="font-mono text-xs tracking-widest text-neutral-500 uppercase"
        >
          The line
        </h2>
        <p className="mt-3 text-sm text-neutral-600 dark:text-neutral-400">
          Cinematography, photography, animation, photogrammetry and heritage
          research, in the order they happened.
        </p>
        <ol className="mt-6 flex flex-col">
          {TIMELINE.map((entry) => (
            <li
              key={`${entry.period}-${entry.role}`}
              className="grid grid-cols-[5.5rem_1fr] gap-x-4 border-t border-neutral-200 py-4 dark:border-neutral-800"
            >
              <span className="font-mono text-xs text-neutral-500 tabular-nums">
                {entry.period}
              </span>
              <span>
                <span className="block text-[15px]">{entry.role}</span>
                {entry.detail && (
                  <span className="mt-1 block text-sm leading-relaxed text-neutral-600 dark:text-neutral-400">
                    {entry.detail}
                  </span>
                )}
              </span>
            </li>
          ))}
        </ol>
      </section>

      <section aria-labelledby="institutions" className="mt-16">
        <h2
          id="institutions"
          className="font-mono text-xs tracking-widest text-neutral-500 uppercase"
        >
          Institutions
        </h2>
        <p className="mt-3 text-sm text-neutral-600 dark:text-neutral-400">
          Four organisations that can be asked about this work without going
          through me.
        </p>
        <ul className="mt-6 flex flex-col">
          {INSTITUTIONS.map((institution) => (
            <li
              key={institution.name}
              className="border-t border-neutral-200 py-4 dark:border-neutral-800"
            >
              <p className="text-[15px]">{institution.name}</p>
              <p className="mt-1 text-sm leading-relaxed text-neutral-600 dark:text-neutral-400">
                {institution.relationship}
              </p>
              {institution.href && (
                <p className="mt-2">
                  <a
                    href={institution.href}
                    target="_blank"
                    rel="noreferrer"
                    className="text-sm underline underline-offset-4 focus-visible:outline-2 focus-visible:outline-offset-4"
                  >
                    {institution.hrefLabel ?? "Source"} ↗
                  </a>
                </p>
              )}
            </li>
          ))}
        </ul>
      </section>

      <section aria-labelledby="verifiable" className="mt-16">
        <h2
          id="verifiable"
          className="font-mono text-xs tracking-widest text-neutral-500 uppercase"
        >
          Checkable
        </h2>
        <dl className="mt-6 grid grid-cols-[auto_1fr] gap-x-6 gap-y-2 text-[15px]">
          {VERIFIABLE.map((fact) => (
            <div key={fact.label} className="contents">
              <dt className="font-mono text-xs text-neutral-500">
                {fact.label}
              </dt>
              <dd>
                {fact.href ? (
                  <a
                    href={fact.href}
                    target="_blank"
                    rel="noreferrer"
                    className="underline underline-offset-4 focus-visible:outline-2 focus-visible:outline-offset-4"
                  >
                    {fact.value} ↗
                  </a>
                ) : (
                  fact.value
                )}
              </dd>
            </div>
          ))}
        </dl>
      </section>

      <section aria-labelledby="contact" className="mt-16">
        <h2
          id="contact"
          className="font-mono text-xs tracking-widest text-neutral-500 uppercase"
        >
          Contact
        </h2>
        <div className="mt-6">
          <Contact />
        </div>
        <ul className="mt-6 flex flex-wrap gap-x-5 gap-y-2">
          {PROFILES.map((profile) => (
            <li key={profile.label}>
              <a
                href={profile.href}
                target="_blank"
                rel="noreferrer"
                className="text-sm text-neutral-600 underline underline-offset-4 hover:text-neutral-950 focus-visible:outline-2 focus-visible:outline-offset-4 dark:text-neutral-400 dark:hover:text-neutral-50"
              >
                {profile.label} ↗
              </a>
            </li>
          ))}
        </ul>
        <p className="mt-8 text-[15px] leading-relaxed text-neutral-600 dark:text-neutral-400">
          Online you may also find me as Shourov, Shourov Hassan or Khondoker
          Hassan. They are all me.
        </p>
      </section>
    </div>
  );
}
